version: "3.9"
services:
  fastapi:
    container_name: fastapi
    build: .
    working_dir: /usr/src/app
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/usr/src/app
    ports:
      - "80:8000"
    restart: on-failure
  db:
    container_name: mydb
    image: mysql:8.4
    ports:
        - "32001:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root